# Configure parameter values for development time. These will be overriden at runtime with the user provided data
NAAS_CLUSTER: GEO_TEST_1_LTE_HUAWEI
#CLIENT_ID: ''
#CLIENT_SECRET: ''
CLIENT_ID: 'SZc5nxWR2HNT3zL6xr8xIn7S1bQ'
CLIENT_SECRET: 'ChXh2d1AvLqYDfcQopBRFq72D1k'
