application:
  meta:
    name: TGE_MOCN_PHYSICALS
    description: This is a prototype chime application
    author: niklas.buchmueller@telefonica.com
  schema:
    - name: NAAS_CLUSTER
      displayName: NaaS Cluster
      description: Name of NaaS cluster for this application.
      defaultValue: ""
      type: string
      group: General Settings
    - name: CLIENT_ID
      displayName: Cliend Id
      description: Application client id
      defaultValue:
      type: string
      group: General Settings
    - name: CLIENT_SECRET
      displayName: Client Secret
      description: Application client secret
      defaultValue:
      type: string
      group: General Settings
